name: Phpunit Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update composer
      run: make

    - name: phpunit
      id: phpunit
      run: make test

    - name: Send email notification on success
      if: ${{ job.status == 'success' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mail.seventeeninfo.fr
        server_port: 587
        username: '${{secrets.SMTP_USER}}'
        password: '${{secrets.SMTP_PASSWORD}}'
        subject: 'Build Success'
        body: 'Congratulations! Your PHPUnit build was successful.'
        to: 'l.marque@it-students.fr'

    - name: Send email notification on failure
      if: ${{ job.status == 'failure' }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mail.seventeeninfo.fr
        server_port: 587
        username: '$${{secrets.SMTP_USER}}'
        password: '${{secrets.SMTP_PASSWORD}}'
        subject: 'Build Fail'
        body: 'Oops! Your PHPUnit build has failed.'
        to: 'l.marque@it-students.fr'
